global:
  sendAnonymousUsage: false

api:
  dashboard: true
  insecure: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

log:
  level: INFO
  format: common

entryPoints:
  web:
    address: ":80"
    forwardedHeaders:
      insecure: true
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
    asDefault: true
    http:
      tls:
        certresolver: myresolver
  mongo:
    address: ":27017"
  redis:
    address: ":6379"
  ping:
    address: ":8082"
  rabbitmq:
    address: ":5672"
  rabbitmq-admin:
    address: ":15672"
  jaeger-1:
    address: ":57282/udp"
  jaeger-2:
    address: ":6831/udp"

ping:
  entryPoint: ping

tracing:
  jaeger: {}

serversTransport:
  insecureSkipVerify: true

#certificatesresolvers:
#  myresolver:
#    acme:
#      dnschallenge:
#        provider: duckdns
#        delaybeforecheck: 20
#      storage: /letsencrypt/acme.json
#      email: davidbaeriksson@gmail.com
