name: Deploy

on:
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - uses: omahn/wireguard-ssh-github-action@v1.4
        with:
          # Required. IP address of your WireGuard peer/endpoint. Must be publicly reachable.
          peer_ip: ${{ WIREGUARD_PEER_IP }}
          # Required. SSH public key as a string.
          ssh_public_key: ${{ SSH_PUB_KEY }}
          # Port of WireGuard peer.
          peer_port: ${{ WIREGUARD_PEER_PORT }}
          # Private IP of GitHub WireGuard peer.
          github_ip: ${{ INTERNAL_IP }}
          # Seconds to wait for SSH connection.
          ssh_connection_timeout: '300'
          # Seconds to timeout SSH session.
          session_timeout: 3600
      - name: Deploy
        run: ls -lh

