name: Deploy

on:
  workflow_dispatch:

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest

    steps:
      - uses: niwee-productions/actions-ssh-wireguard@beta-0.1
        with:
          # Required: The SSH user to connect as.
          user: ${{ secrets.SSH_USER }}
          # Required: The SSH host to connect to.
          host: ${{ secrets.SSH_IP }}
          # Required: The SSH port to connect to.
          port: ${{ secrets.SSH_PORT }}
          # Required: The SSH private key to use for authentication.
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Required: The WireGuard configuration to use for the tunnel.
          conf: ${{ secrets.WIREGUARD_CONF }}
          # Required: The script to run on the remote host after the tunnel is established.
          script: "ls -lh"

