name: Deploy

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}

jobs:
  deploy:
    name: Setup wireguard connection, and run ssh-script
    runs-on: ubuntu-latest

    steps:
      - uses: seppaleinen/actions-ssh-wireguard@0.6-dev
        with:
          # Required: The SSH user to connect as.
          user: ${{ secrets.SSH_USER }}
          # Required: The SSH host to connect to.
          host: ${{ secrets.SSH_IP }}
          # Required: The SSH port to connect to.
          port: ${{ secrets.SSH_PORT }}
          # Required: The SSH private key to use for authentication.
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # Required: The WireGuard configuration to use for the tunnel.
          conf: ${{ secrets.WIREGUARD_CONFIG }}
          # Required: The script to run on the remote host after the tunnel is established.
          script: "cd workspace/integration-tests && git stash && git pull && git stash pop && docker compose pull && docker compose up -d && docker system prune -f"

