# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
        cache-dependency-path: cypress/package-lock.json
    - name: Start containers
      run: |
        docker-compose -f "docker-compose.yml" up -d || docker-compose -f "docker-compose.yml" up -d
        docker cp datasubset/tmdb.movie.json mongo:/
        docker cp datasubset/tmdb.flattened_movie.json mongo:/
        docker exec mongo mongoimport -d tmdb -c movie --mode upsert --jsonArray --type json --file tmdb.movie.json
        docker exec mongo mongoimport -d tmdb -c movie --mode upsert --jsonArray --type json --file tmdb.flattened_movie.json
        npm --prefix cypress install
        sleep 120
        npm --prefix cypress run cypress:test
      shell: bash
    - name: Check errors
      if: ${{ failure() }}
      run: docker compose logs && docker ps -a
    - name: Stop containers
      if: ${{ always() }}
      run: docker-compose -f "docker-compose.yml" down

